#eureka 服务注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#client服务端口
server:
  port: 8762
#client服务name
spring:
  application:
    name: service-provider
  # zipkin调用链
  zipkin:
    base-url: http://localhost:9411 #服务链路追踪zipkin服务地址
  sleuth:
      sampler:
        percentage: 1.0 #100%的概率将链路的数据上传给Zipkin Server，在默认的情况下，该值为0.1
#    service:
#      name: sleuth-zipkin-server
