server:
  port: 8761

#[默认情况下eurekaserver也是一个eurekaclient,必须指定一个server]
eureka:
  instance:
    hostname: localhost
  client:
    #[registerWithEureka: false和fetchRegistry: false表明当前应用是一个eureka server]
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/