eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-consumer-feign
  # zipkin调用链
  zipkin:
    base-url: http://localhost:9411

#feign开启断路器
feign:
 hystrix:
  enabled: true